src/Entity/Informations.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource
 * @ORM\Entity(repositoryClass="App\Repository\InformationsRepository")
 */
class Informations
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tel_interna;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cv_url;

    public function getId()
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getTelInterna(): ?string
    {
        return $this->tel_interna;
    }

    public function setTelInterna(?string $tel_interna): self
    {
        $this->tel_interna = $tel_interna;

        return $this;
    }

    public function getCvUrl(): ?string
    {
        return $this->cv_url;
    }

    public function setCvUrl(?string $cv_url): self
    {
        $this->cv_url = $cv_url;

        return $this;
    }
}

src/Form/InformationsType.php
<?php

namespace App\Form;

use App\Entity\Informations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InformationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('tel')
            ->add('tel_interna')
            ->add('cv_url')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Informations::class,
        ]);
    }
}

src/Controller/InformationsController.php
<?php

namespace App\Controller;

use App\Entity\Informations;
use App\Form\InformationsType;
use App\Repository\InformationsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/informations")
 */
class InformationsController extends Controller
{
    /**
     * @Route("/", name="informations_index", methods="GET")
     */
    public function index(InformationsRepository $informationsRepository): Response
    {
        return $this->render('informations/index.html.twig', ['informations' => $informationsRepository->findAll()]);
    }

    /**
     * @Route("/new", name="informations_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $information = new Informations();
        $form = $this->createForm(InformationsType::class, $information);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($information);
            $em->flush();

            return $this->redirectToRoute('informations_index');
        }

        return $this->render('informations/new.html.twig', [
            'information' => $information,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="informations_show", methods="GET")
     */
    public function show(Informations $information): Response
    {
        return $this->render('informations/show.html.twig', ['information' => $information]);
    }

    /**
     * @Route("/{id}/edit", name="informations_edit", methods="GET|POST")
     */
    public function edit(Request $request, Informations $information): Response
    {
        $form = $this->createForm(InformationsType::class, $information);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('informations_edit', ['id' => $information->getId()]);
        }

        return $this->render('informations/edit.html.twig', [
            'information' => $information,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="informations_delete", methods="DELETE")
     */
    public function delete(Request $request, Informations $information): Response
    {
        if ($this->isCsrfTokenValid('delete'.$information->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($information);
            $em->flush();
        }

        return $this->redirectToRoute('informations_index');
    }
}

templates/informations/_delete_form.html.twig
<form method="post" action="{{ path('informations_delete', {'id': information.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ information.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/informations/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier les informations{% endblock %}

{% block body %}

<div>
    <a class="text-muted" href="{{ path('logout') }}">Déconnexion</a>
</div>
<div class="nav">
    <a class="lienPages" href="{{ path('projets_index') }}">Projets</a>
    <a class="lienPages" href="{{ path('images_index') }}">Images</a>
    <a class="lienPages" href="{{ path('competences_index') }}">Compétences</a>
    <a class="lienPages" href="{{ path('informations_index') }}">Informations</a>
</div
    <h1>Modifier les informations</h1>

    {{ include('informations/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    {{ include('informations/_delete_form.html.twig') }}

    <a href="{{ path('informations_index') }}">Retour à la liste</a>

{% endblock %}

templates/informations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Informations{% endblock %}

{% block body %}

<a class="text-muted" href="{{ path('logout') }}">Déconnexion</a>

<div class="nav">
    <a class="lienPages" href="{{ path('projets_index') }}">Projets</a>
    <a class="lienPages" href="{{ path('images_index') }}">Images</a>
    <a class="lienPages" href="{{ path('competences_index') }}">Compétences</a>
    <a class="lienPages" href="{{ path('informations_index') }}">Informations</a>
</div>
    <h1>Informations</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Tel</th>
                <th>Tel_interna</th>
                <th>Cv_url</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for information in informations %}
            <tr>
                <td>{{ information.id }}</td>
                <td>{{ information.description }}</td>
                <td>{{ information.tel }}</td>
                <td>{{ information.telInterna }}</td>
                <td>{{ information.cvUrl }}</td>
                <td>
                    <div class="action">
                        <a class="stylebouton" href="{{ path('informations_show', {'id': information.id}) }}">Voir</a>
                        <a class="stylebouton" href="{{ path('informations_edit', {'id': information.id}) }}">Modifier</a>
                        {{ include('informations/_delete_form.html.twig') }}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="commande">
        <a class="stylebouton1" href="{{ path('informations_new') }}">Créer une information</a>
    </div>
{% endblock %}

templates/informations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle information{% endblock %}

{% block body %}
<a class="text-muted" href="{{ path('logout') }}">Déconnexion</a>

<div class="nav">
    <a class="lienPages" href="{{ path('projets_index') }}">Projets</a>
    <a class="lienPages" href="{{ path('images_index') }}">Images</a>
    <a class="lienPages" href="{{ path('competences_index') }}">Compétences</a>
    <a class="lienPages" href="{{ path('informations_index') }}">Informations</a>
</div>
    <h1>Créer une nouvelle information</h1>

    {{ include('informations/_form.html.twig') }}

    <a href="{{ path('informations_index') }}">Retour à la liste</a>
{% endblock %}

templates/informations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Informations{% endblock %}

{% block body %}
<a class="text-muted" href="{{ path('logout') }}">Déconnexion</a>

<div class="nav">
    <a class="lienPages" href="{{ path('projets_index') }}">Projets</a>
    <a class="lienPages" href="{{ path('images_index') }}">Images</a>
    <a class="lienPages" href="{{ path('competences_index') }}">Compétences</a>
    <a class="lienPages" href="{{ path('informations_index') }}">Informations</a>
</div>
    <h1>Informations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ information.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ information.description }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ information.tel }}</td>
            </tr>
            <tr>
                <th>Tel_interna</th>
                <td>{{ information.telInterna }}</td>
            </tr>
            <tr>
                <th>Cv_url</th>
                <td>{{ information.cvUrl }}</td>
            </tr>
        </tbody>
    </table>
<p>

<div class="commande1">
    <a class="stylebouton1" href="{{ path('informations_edit', {'id': information.id}) }}">Modifier</a>
    {{ include('informations/_delete_form.html.twig') }}</p>
</div>
<div>
    <a href="{{ path('informations_index') }}">Retour à la liste</a>
</div>
{% endblock %}